### PR TITLE
Improve support for COP computation

### LINKED ISSUE #90: sensor.aquarea_cop
I control now already a few days meanwhile 2 heat pumps with 2 Heishamon.
I use this integration for Homeassistant. For this thank you.....

While browsing the sensors I noticed **sensor.aquarea_cop** and **sensor.aquarea_cop_2**

But neither of the two sensors displays data!

Can I fix this or is this a bug in the integration?

Sincerly Axel

### PR DESCRIPTION
**Pull request by kamaradclimber**
We now recompute COP from mqtt message instead of doing a dance with dynamic templates.
It allows to support multiple heatpumps easily and support users who would change entity_ids.

Fix #90

### CODE REVIEW

**Comment by Bucky2k** [comment]
Is this a breaking change?  Former COP value changes to "unknown" after update from 1.2.0 to 1.2.2 and stay like that.

**Comment by kamaradclimber** [comment]
It is in unknown state when there is no power production/consumption. Previous sensor would return a cop of 0.
Which behavior do you think would be the most relevant?

**Comment by Bucky2k** [comment]
In terms of data recording (influxdb) I preferred the 0.0 at idle

**Comment by Bucky2k** [comment]
Also, the naming prefix for all other values is Aquarea. Aquarea COP instead of just COP would be more consistent, right?

**Pull request merged**
