### PR TITLE
Fix SetZ1HeatRequestTemp range when in direct mode

### PR DESCRIPTION
**Pull request by hannut**
* Range is from 20c to 60c when using direct heating mode
* Heat_Pump_Model	5	IDU:WH-SXC12H9E8, ODU:WH-UX12HE8

### CODE REVIEW

**Comment by geduxas** [comment]
It should'nt be so straight! Heishamon has flags for heating mode, so values should be in heating mode range.. also +60 is for T-CAP only,

**Review by kamaradclimber — APPROVED** [review]

**Comment by kamaradclimber** [comment]
@geduxas what do you suggest?

**Comment by geduxas** [comment]
> @geduxas what do you suggest?

There is 2 main heating mode, direct and compensation. It's possible to get it from TOP76	Heating_Mode.
Compensation curve values are strict, from -5 to +5.

For direct temperature it's splitting in two ranges, direct room temperature, and directly water temperature,

For direct water temperature range is +20°-55° 
And only for t-cap's you can set it to 60° and inly till -10°.. -15 and below it will be max +55°.

And for room temperature.. actually I don't know ranges for it :) 


Thermostat element should be tied to TOP76	Heating_Mode,
If it's compensation curve, range should be -5 -+5, if it's direct water heating

**Comment by hannut** [comment]
Well, the original 7-45 hard coded range doesn't work as expected either. We have colder than -30c this week and the old value of 45 is too little to keep the house warm :)

Does this patch make it worse than it was before? At least now I can use the whole usable range.

You are correct that these ranges should populate automatically. It's not prefect but solves the problem of not getting enough heat

**Comment by geduxas** [comment]
> Well, the original 7-45 hard coded range doesn't work as expected either. We have colder than -30c this week and the old value of 45 is too little to keep the house warm :)
> 
> Does this patch make it worse than it was before? At least now I can use the whole usable range.
> 
> You are correct that these ranges should populate automatically. It's not prefect but solves the problem of not getting enough heat

Wow -30 :D will pump work in this temperature? Lowest i have got was -24, and truly +43 was enough for my house :) 

Yes it will not make worse.. just if it possible it could be better to make it work as it should instead of dirty hack's ;)

**Comment by hannut** [comment]
The T-CAP has 3, 6 and 9 kw electric heater resistors which activate one by one when the pump can't keep up. I'm getting about 1.2 - 1.5 cop currently. It's only a few weeks like this in a year. Some years we don't go below -25.

**Comment by kamaradclimber** [comment]
At the moment I don't see a better solution than just extend the range.
If I understand correctly your explanation @geduxas , the ideal solution is:
- detect heating mode thanks to TOP76
- if direct mode, detect if we are setting room temperature or water temperature (how?)
- set the appropriate range, and possibly extend it for models with t-cap

I'll merge this patch for now

**Review by kamaradclimber — APPROVED** [review]

**Comment by kamaradclimber** [comment]
Thanks both for your explanation and patch.

**Comment by kamaradclimber** [comment]
@hannut  I wonder why you updated only Zone1 and not also Zone2

**Pull request merged**
