### PR TITLE
Update Energy to Power for Firmware 3.2

### PR DESCRIPTION
**Pull request by timovd**
Update Energy to Power for Firmware 3.2
https://github.com/Egyras/HeishaMon/releases/tag/v3.2

### CODE REVIEW

**Comment by geduxas** [comment]
@timovd you should support both values, don't think that everyone will upgrade it soon :)

**Comment by timovd** [comment]
If you're on fw <=3.1, you should use the old version of the integration. You cannot support all values forever.

**Comment by Bucky2k** [comment]
Not so sure about that. People install HA, HACS and the Plugin being interested in onboarding Heishamon. An the per default/latest Version it does not work. Lots of complaints and issues will be raised. 

Heishamon is often bought out of the box, I bet a significant portion of people do not know FW can be updated

**Comment by kamaradclimber** [comment]
> If you're on fw <=3.1, you should use the old version of the integration. You cannot support all values forever.

FW 3.2 was released 2 days ago! 
So I intend to keep compatibility with 3.1 and previous versions for some time (at least until I update my heishamon and probably for a lot longer).

AS @Bucky2k wrote, people can upgrade HA and custom integration very easily. Upgrading a firmware is not the same thing.

**Comment by kamaradclimber** [comment]
Anyway, thanks for the contribution. I think I'll merge as is this week end and add a patch to be backward compatible with version <= 3.1.

This discussion also gave me the idea of #133 which I hope I'll be able to implement in order to give a nice nudge for updates.

**Pull request merged**
