### PR TITLE
Fix compensation curve heating values, update HeatPumpType models

### PR DESCRIPTION
**Pull request by ekouters**
The descriptions of the heating compensation curve for Z1 and Z2 have the "lowest" and "highest" swapped.
Initially I thought the installer configured it incorrectly, but it turns out the description was incorrect. :-)

My heatpump was not recognized (T-CAP J-series 12kW), so I have updated the `models.py` with the attached script.

### CODE REVIEW

**Comment by Bucky2k** [comment]
Not so sure about that, it's ok on my side. Remark: It's saying e.g. "temperature at lowest point on heat curve". That means: Low point on heat curve, e.g. -10°C outside temp, shall yield xx°C outlet temperature". This value will of course be the high one, as the other will be low on high outside temperatures. So it is counter intuitive on the first read, but correct

**Comment by geduxas** [comment]
Also it's possible that J series HeatPump have little bit different registers.. need to double check that too..

**Comment by geduxas** [comment]
Never noticed that, but it's seam's that namming is little misleading.. 

Screenshot_2023-08-31-08-27-30-36_c3a231c25ed346e59462e84656a70e50

Also same is with Z2 too.

**Comment by Bucky2k** [comment]
Ahh, I see. The naming in Heishamon is okay, but in HA not. Never noticed until today
Screenshot_20230831_075558_Home Assistant

**Comment by ekouters** [comment]
> Ahh, I see. The naming in Heishamon is okay, but in HA not. 
This is exactly what this PR attempts to fix.

**Comment by geduxas** [comment]
> > Ahh, I see. The naming in Heishamon is okay, but in HA not.
> 
> This is exactly what this PR attempts to fix. :-)

Yes, but it's problem only with outside temperature naming.. for heat in lowest point i think it's correct :)

**Comment by ekouters** [comment]
> > > Ahh, I see. The naming in Heishamon is okay, but in HA not.
> > 
> > 
> > This is exactly what this PR attempts to fix. :-)
> 
> Yes, but it's problem only with outside temperature naming.. for heat in lowest point i think it's correct :)

I see what you mean.
The naming does seem very confusing to me.

Here's my train of thoughts.
The MQTT topics are:
- `Z1_Heat_Curve_Target_High_Temp`
- `Z1_Heat_Curve_Target_Low_Temp`
- `Z1_Heat_Curve_Outside_High_Temp`
- `Z1_Heat_Curve_Outside_Low_Temp`

This image comes from the service manual:
image

The confusion comes from the `Low_Temp` and `High_Temp`.
These Low and High temperatures refer to the **outside temperature**, not the **water temperature**.
With a low outside temperature (`Z1_Heat_Curve_Outside_Low_Temp`), it uses the Low_Temp target (`Z1_Heat_Curve_Target_Low_Temp`).

These are **currently** described as:
- Highest outside temperature on the heating curve (`Z1_Heat_Curve_Outside_Low_Temp`)
- Target temperature at highest point on heating curve (`Z1_Heat_Curve_Target_Low_Temp`)

My PR attempts to correct these to:
- Lowest outside temperature on the heating curve (`Z1_Heat_Curve_Outside_Low_Temp`)
- Target temperature at lowest point on heating curve (`Z1_Heat_Curve_Target_Low_Temp`)

I agree my PR is incorrect on updating the Target temperature description.
I'm also unhappy with the description in general (lowest/highest point on heating curve).
Instead, I would suggest "Target water temperature at lowest outside temperature on the heating curve".
What do you guys think?

**Comment by geduxas** [comment]
@ekouters i think you're free to make changes :)

**Comment by kamaradclimber** [comment]
Hello, thanks both for the patch and comments.
I've merged it (I messed up in git so the PR appeared as closed) and it's part of https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.0.8

**Pull request closed without merging**
