### PR TITLE
🎨 Improve quiet mode descriptions

### PR DESCRIPTION
**Pull request by kamaradclimber**

### CODE REVIEW

**Comment by geduxas** [comment]
Why quaet mode's related to power consumption? 
Truly quaet mode is for silence external unit for noice.. power consumption is side efect for that..

**Comment by kamaradclimber** [comment]
I'm using the description from the doc [here](https://github.com/IgorYbema/HeishaMon/blob/main/MQTT-Topics.md?plain=1#L37)

**Comment by wltng** [comment]
Hi @kamaradclimber,
I agree with @geduxas. The descriptions don't say anything about the quite mode, but about the heat pump power.
I personally do not find these descriptions very intuitive. Panasonic also uses off, 1, 2 and 3 as values.

Besides, this was a breaking change. My automations setting quiet mode suddenly didn't work anymore... It wasn't mentioned as such in the release notes....

**Comment by kamaradclimber** [comment]
Hello,

I'm ok to revert the change. Could one of you update the upstream documentation to avoid future confusion?

**Pull request merged**
